apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: your-tls
  namespace: your-portfolio  # Ensure this matches the namespace where you want to store the certificate
spec:
  secretName: your-tls  # This should be the name of the secret where the certificate will be stored
  issuerRef:
    name: letsencrypt-prod  # Must match the name of your ClusterIssuer
    kind: ClusterIssuer
  commonName: example.com  # The domain you are securing
  dnsNames:
  - example.com  # List of domains to be covered by the certificate
